spec:
  inputs:
    java-version:
      description: Java version to use for the jobs
      type: string
      default: "25"
      options:
        - "17"
        - "21"
        - "25"
    buildpacks-tag:
      description: Builder image type to use for building the application
      type: string
      default: "musl"
      options:
        - "musl"
        - "glibc"
        - "noble"
    test:
      description: Run tests
      type: string
      default: yesss
      options:
        - yesss
        - nooo
    sonar:
      description: Run SonarQube analysis
      type: string
      default: yesss
      options:
        - yesss
        - nooo
    build:
      description: Build the project
      type: string
      default: nooo
      options:
        - yesss
        - nooo
    deploy-dev:
      description: Build and deploy in development environment
      type: string
      default: nooo
      options:
        - yesss
        - nooo
    deploy-prod:
      description: Build and deploy in production environment
      type: string
      default: nooo
      options:
        - yesss
        - nooo
    dev-replicas:
      description: Number of replicas for the development environment
      type: number
      default: 1
    prod-replicas:
      description: Number of replicas for the production environment
      type: number
      default: 1
    dev-java-opts:
      description: Java VM options for the development environment
      type: string
      default: ""
    prod-java-opts:
      description: Java VM options for the production environment
      type: string
      default: ""
    dev-additional-spring-profiles:
      description: Additional Spring profiles for the development environment
      type: string
      default: "default"
    prod-additional-spring-profiles:
      description: Additional Spring profiles for the production environment
      type: string
      default: "default"
    test-runner:
      description: Run the test job on a specific runner
      type: string
      default: cpdi
      options:
        - cpdi
        - runner-#01
        - runner-#02
        - runner-#03
    build-runner:
      description: Run the build job on a specific runner
      type: string
      default: cpdi
      options:
        - cpdi
        - runner-#01
        - runner-#02
        - runner-#03
    packages:
      type: string
      description: List of packages to install in the run image
      default: ""

---

stages:
  - test
  - build
  - deploy

variables:
  GIT_DEPTH: "0"  # Tells git to fetch all the branches of the project, required by the analysis task

  MAVEN_VERSION: 3.9.16
  JAVA_VERSION: $[[ inputs.java-version ]]

  TEST: $[[ inputs.test ]]
  SONAR: $[[ inputs.sonar ]]
  BUILD: $[[ inputs.build ]]

  DEPLOY_DEV: $[[ inputs.deploy-dev ]]
  DEPLOY_PROD: $[[ inputs.deploy-prod ]]

  MAVEN_LOCAL_REPO: ".m2/repository"
  MAVEN_OPTS: "-Dmaven.repo.local=$MAVEN_LOCAL_REPO"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml -ntp" # -B

  TEST_RUNNER: $[[ inputs.test-runner ]]
  BUILD_RUNNER: $[[ inputs.build-runner ]]

.default:
  image: docker.io/library/ubuntu:24.04
  retry: 0
  tags:
    - cpdi
  after_script:
    - echo Job started by user "$GITLAB_USER_NAME" in branch "$CI_COMMIT_BRANCH" finished with status "$CI_JOB_STATUS"!

.cache-maven: &cache-maven
  - key: "maven-local-repo"
    policy: pull-push
    paths:
      - "$MAVEN_LOCAL_REPO"

.script-wget-maven-setting: &script-curl-maven-setting
  - mkdir -p .m2
  - |
    curl -ksSL \
      -H "PRIVATE-TOKEN: ${DEV_GITLAB_TOKEN}" \
      "${CI_API_V4_URL}/projects/${TEMPLATES_PROJECT_ID}/repository/files/${TEMPLATES_PROJECT_MAVEN_SETTINGS_XML_PATH}/raw?ref=main" \
      -o .m2/settings.xml

.pom-src-changeset-template: &pom-src-changeset-template
  changes:
    - pom.xml
    - src/**/*
    - .gitlab-ci.yml

test:
  extends: .default
  tags:
    - $TEST_RUNNER
  image: docker.io/maven:${MAVEN_VERSION}-eclipse-temurin-${JAVA_VERSION}-noble
  stage: test
  coverage: '/Total.*?(\d{1,3})%/'
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    VAULT_URI: $CPDI_VAULT_URI
    VAULT_TOKEN: $DEV_VAULT_TOKEN
    LOGSTASH_URI: ${DEV_LOGSTASH_URI_SPRING_BOOT}
  cache:
    - *cache-maven
    - key: "sonar-cache"
      paths:
        - "${SONAR_USER_HOME}/cache"
  before_script:
    - *script-curl-maven-setting
  script:
    - mvn $MAVEN_CLI_OPTS verify -Dspring.profiles.active=test
    - |
      if [ "$SONAR" == "yesss" ]; then
        mvn $MAVEN_CLI_OPTS sonar:sonar || true
        grep -o "<tfoot>.*</tfoot>" target/site/jacoco/index.html
      fi
  rules:
    - if: $TEST == "yesss"
      <<: *pom-src-changeset-template
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
      coverage_report:
        coverage_format: jacoco
        path: target/site/jacoco/jacoco.xml

build:
  extends: .default
  image: docker.io/maven:${MAVEN_VERSION}-eclipse-temurin-${JAVA_VERSION}-alpine
  tags:
    - $BUILD_RUNNER
  variables:
    TAG: $[[ inputs.buildpacks-tag ]]
    PACKAGES: $[[ inputs.packages ]]
  resource_group: $CI_COMMIT_BRANCH
  stage: build
  cache:
    - *cache-maven
  before_script:
    - apk update
    - apk add --no-cache docker-cli docker-cli-buildx
  script:
    - *script-curl-maven-setting
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - |
      if [ "$TAG" = "glibc" ]; then
        export SHA256="fb75ce539479c5cafb3cf3ca416b9390a716cb6451c98b5f28d6bc1fa132815b"
      elif [ "$TAG" = "musl" ]; then
        export SHA256="4d36dc5fc2370589e804ab42ae4fd9da0745220570e50411cd79a9c3c23ecf2f"
      fi

    - |
      if [ "$TAG" = "noble" ]; then
        export BUILDER_IMAGE="docker.io/paketobuildpacks/builder-noble-java-tiny:latest"
        export BASE_IMAGE="docker.io/paketobuildpacks/ubuntu-noble-run:latest"
        export PACKAGES="$PACKAGES wget"
      else
        export BUILDER_IMAGE="docker.io/bellsoft/buildpacks.builder:$TAG"
        export BASE_IMAGE="docker.io/bellsoft/buildpacks.alpaquita-run:$TAG"
      fi
    - docker pull $BUILDER_IMAGE
    - docker pull $BASE_IMAGE
    - |
      if [ -n "$PACKAGES" ]; then
        curl -skSL \
          -H "PRIVATE-TOKEN: ${DEV_GITLAB_TOKEN}" \
          "${CI_API_V4_URL}/projects/${TEMPLATES_PROJECT_ID}/repository/files/${TEMPLATES_PROJECT_BUILDPACKS_RUN_DOCKERFILE_PATH}/raw?ref=main" \
          -o Dockerfile
      
        export RUN_IMAGE="gitlab-ci.cpdi.dev/job/$CI_JOB_ID/buildpacks-run:$TAG"
      
        docker buildx build \
          --pull \
          --platform linux/amd64 \
          --build-arg BASE_IMAGE=$BASE_IMAGE \
          --build-arg PACKAGES="$PACKAGES" \
          -t $RUN_IMAGE .
      else
        export RUN_IMAGE=$BASE_IMAGE
      fi
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        export ENVIRONMENT="production"
      elif [ "$CI_COMMIT_BRANCH" = "develop" ]; then
        export ENVIRONMENT="development"
      else
        export ENVIRONMENT="$CI_COMMIT_BRANCH"
      fi
    - |
      mvn $MAVEN_CLI_OPTS clean spring-boot:build-image \
        -DskipTests=true \
        -Ddocker.publishRegistry.url="$CI_REGISTRY" \
        -Ddocker.publishRegistry.username="$CI_REGISTRY_USER" \
        -Ddocker.publishRegistry.password="$CI_REGISTRY_PASSWORD" \
        -Dspring-boot.build-image.createdDate=now \
        -Dspring-boot.build-image.publish=false \
        -Dspring-boot.build-image.pullPolicy=IF_NOT_PRESENT \
        -Dspring-boot.build-image.builder=$BUILDER_IMAGE \
        -Dspring-boot.build-image.runImage=$RUN_IMAGE \
        -Dspring-boot.build-image.imageName=$CI_REGISTRY_IMAGE:$ENVIRONMENT
    - docker push $CI_REGISTRY_IMAGE:$ENVIRONMENT
    - docker rmi $CI_REGISTRY_IMAGE:$ENVIRONMENT
    - if [ -n "$PACKAGES" ]; then docker rmi $RUN_IMAGE; fi
  rules:
    - if: ( $CI_COMMIT_BRANCH == "develop" && $DEPLOY_DEV == "yesss" ) || ( $CI_COMMIT_BRANCH == "main" && $DEPLOY_PROD == "yesss" )
      <<: *pom-src-changeset-template
    - if: $BUILD == "yesss"
      <<: *pom-src-changeset-template

.deploy-template: &deploy-template
  extends: .default
  image: docker.io/alpine:3.23.4
  stage: deploy
  resource_group: $CI_COMMIT_BRANCH
  variables:
    DEV_REPLICAS: $[[ inputs.dev-replicas ]]
    PROD_REPLICAS: $[[ inputs.prod-replicas ]]

    DEV_JAVA_OPTS: $[[ inputs.dev-java-opts ]]
    PROD_JAVA_OPTS: $[[ inputs.prod-java-opts ]]

    DEV_ADD_SPRING_PROFILES: $[[ inputs.dev-additional-spring-profiles ]]
    PROD_ADD_SPRING_PROFILES: $[[ inputs.prod-additional-spring-profiles ]]

    PROJECT_DIR: /opt/docker/compose/stacks/$CI_PROJECT_NAME
    DOCKER_CONFIG: $PROJECT_DIR/.docker

    RETRIES: 10
    TIMEOUT: 30
  before_script:
    - apk update
    - apk add --no-cache openssh-client
  script:
    - |
      if [ "$CI_COMMIT_BRANCH" = "main" ]; then
        env="prod"
        ENV="PROD"
        ENVIRONMENT="production"
      elif [ "$CI_COMMIT_BRANCH" = "develop" ]; then
        env="dev"
        ENV="DEV"
        ENVIRONMENT="development"
      fi
      
      VAR_VM_IP=${ENV}_VM_IP
      export VM_IP=$(printenv $VAR_VM_IP)
      
      VAR_SSH_PORT=${ENV}_VM_SSH_PORT
      export SSH_PORT=$(printenv $VAR_SSH_PORT)
      
      VAR_JAVA_OPTS=${ENV}_JAVA_OPTS
      export JAVA_OPTS=$(printenv $VAR_JAVA_OPTS)
      
      VAR_REPLICAS=${ENV}_REPLICAS
      export REPLICAS=$(printenv $VAR_REPLICAS)
      
      VAR_VAULT_TOKEN=${ENV}_VAULT_TOKEN
      export VAULT_TOKEN=$(printenv $VAR_VAULT_TOKEN)
      
      VAR_LOGSTASH_URI=${ENV}_LOGSTASH_URI_SPRING_BOOT
      export LOGSTASH_URI=$(printenv $VAR_LOGSTASH_URI)
      
      VAR_ADD_SPRING_PROFILES="${ENV}_ADD_SPRING_PROFILES"
      export ADD_SPRING_PROFILES=$(printenv $VAR_ADD_SPRING_PROFILES)
      export SPRING_PROFILES_ACTIVE="deploy, docker, $env, $ENVIRONMENT, $ADD_SPRING_PROFILES"

    - |
      export SSH_USER_HOST="$GB_USERNAME@$VM_IP"
      export SSH_ARGS="-i $GB_SSH_PRIVATE_KEY -o StrictHostKeyChecking=no -p $SSH_PORT"
      export SCP_ARGS="-i $GB_SSH_PRIVATE_KEY -o StrictHostKeyChecking=no -P $SSH_PORT"
      export SSH_CMD="ssh $SSH_ARGS $SSH_USER_HOST"

    - |
      if [ ! -f compose.yaml ]; then
        wget -qO compose.yaml \
          --header="PRIVATE-TOKEN: ${DEV_GITLAB_TOKEN}" \
          "${CI_API_V4_URL}/projects/${TEMPLATES_PROJECT_ID}/repository/files/${TEMPLATES_PROJECT_SPRING_BOOT_MAVEN_COMPOSE_TEMPLATE_PATH}/raw?ref=main"
      fi
    - |
      wget -qO check-container-health.sh \
        --header="PRIVATE-TOKEN: ${DEV_GITLAB_TOKEN}" \
        "${CI_API_V4_URL}/projects/${TEMPLATES_PROJECT_ID}/repository/files/${TEMPLATES_PROJECT_CHECK_CONTAINER_HEALTH_SCRIPT_PATH}/raw?ref=main"

    - echo -e PROJECT_NAME="$CI_PROJECT_NAME""\n"IMAGE_NAME="$CI_REGISTRY_IMAGE:$ENVIRONMENT""\n" > .env
    - echo -e VAULT_URI="$DOCKER_VAULT_URI""\n"VAULT_TOKEN="$VAULT_TOKEN""\n" >> .env
    - echo -e SPRING_PROFILES_ACTIVE="$SPRING_PROFILES_ACTIVE""\n"JAVA_OPTS="$JAVA_OPTS""\n" >> .env
    - echo -e REPLICAS="$REPLICAS""\n"LOGSTASH_URI="$LOGSTASH_URI""\n" >> .env
    - echo -e ENVIRONMENT="$ENVIRONMENT""\n" >> .env

    - chmod og= $GB_SSH_PRIVATE_KEY
    - $SSH_CMD "mkdir -p {$PROJECT_DIR,$DOCKER_CONFIG}"
    - scp $SCP_ARGS .env compose.yaml check-container-health.sh $SSH_USER_HOST:$PROJECT_DIR/

    - |
      echo $CI_REGISTRY_PASSWORD | $SSH_CMD \
        "DOCKER_CONFIG=$DOCKER_CONFIG docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY"
    - export DCF="docker compose -f $PROJECT_DIR/compose.yaml"
    - $SSH_CMD "DOCKER_CONFIG=$DOCKER_CONFIG $DCF pull"
    - $SSH_CMD $DCF down --remove-orphans
    - $SSH_CMD $DCF up -d
    - $SSH_CMD chmod +x $PROJECT_DIR/check-container-health.sh
    - $SSH_CMD $PROJECT_DIR/check-container-health.sh $CI_PROJECT_NAME $RETRIES $TIMEOUT
    - $SSH_CMD docker image prune -f || echo 'Prune already running,,, skipping...'
    - $SSH_CMD rm -rf $PROJECT_DIR/.env $DOCKER_CONFIG

.deploy-changeset-template: &deploy-changeset-template
  changes:
    - pom.xml
    - src/**/*
    - .gitlab-ci.yml
    - compose.yaml

deploy-dev:
  <<: *deploy-template
  environment: development
  rules:
    - if: $CI_COMMIT_BRANCH == "develop" && $DEPLOY_DEV == "yesss"
      <<: *deploy-changeset-template

deploy-prod:
  <<: *deploy-template
  tags:
    - prod-deployer
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $DEPLOY_PROD == "yesss"
      <<: *deploy-changeset-template
      when: manual
