x-common: &common
  networks:
    - antonio3a-bridge
  restart: unless-stopped

services:
  pgadmin:
    <<: *common
    image: dpage/pgadmin4:9.1.0
    container_name: antonio3a-pgadmin
    hostname: pgadmin.antonio3a.aaa
    ports:
      - "8380:80"
      - "8343:443"
    volumes:
      - antonio3a-pgadmin-data-vol:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${AAA_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${AAA_PASS}
      - PGADMIN_DEFAULT_USERNAME=${AAA_USER}

  cloudbeaver:
    <<: *common
    container_name: antonio3a-cloudbeaver
    hostname: cloudbeaver.antonio3a.aaa
    image: dbeaver/cloudbeaver:24.1.1
    ports:
      - "8978:8978"
    volumes:
      - antonio3a-cloudbeaver-data-vol:/opt/cloudbeaver/workspace

networks:
  antonio3a-bridge:
    external: true

volumes:
  antonio3a-pgadmin-data-vol:
    external: true
  antonio3a-cloudbeaver-data-vol:
    external: true