x-common: &common
  networks:
    - aaa-bridge
  restart: unless-stopped

services:
  pgadmin:
    <<: *common
    image: dpage/pgadmin4:9.4.0
    container_name: pgadmin
    hostname: pgadmin.antonio3a.aaa
#    ports:
#      - ":80"
#      - ":443"
    volumes:
      - aaa-pgadmin-data-vol:/var/lib/pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${AAA_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${AAA_PASS}
      - PGADMIN_DEFAULT_USERNAME=${AAA_USER}

  cloudbeaver:
    <<: *common
    container_name: cloudbeaver
    hostname: cloudbeaver.antonio3a.aaa
    image: dbeaver/cloudbeaver:25.0.1
#    ports:
#      - ":8978"
    volumes:
      - aaa-cloudbeaver-data-vol:/opt/cloudbeaver/workspace

networks:
  aaa-bridge:
    external: true

volumes:
  aaa-pgadmin-data-vol:
    external: true
  aaa-cloudbeaver-data-vol:
    external: true