x-common : &common
  networks:
    - antonio3a-bridge
  restart: unless-stopped

services:
  mongodb:
    image: mongo:8.0.4
    container_name: antonio3a-mongodb
    hostname: mongodb.antonio3a.aaa
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${AAA_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${AAA_PASS}
    ports:
      - "27017:27017"
    volumes:
      - antonio3a-mongodb-data-vol:/data/db
      - antonio3a-mongodb-config-vol:/data/configdb
    <<: *common 

  neo4j:
    image: neo4j:5.26.0-enterprise
    container_name: antonio3a-neo4j
    hostname: neo4j.antonio3a.aaa
    environment:
      - apoc.export.file.enabled=true
      - apoc.import.file.enabled=true
      - apoc.import.file.use_neo4j_config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/${AAA_PASS}
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    volumes:
      - antonio3a-neo4j-data-vol:/data
      - antonio3a-neo4j-logs-vol:/logs
      - antonio3a-neo4j-plugins-vol:/plugins
      - $AAA_HOME/neo4j/conf/apoc.conf:/var/lib/neo4j/conf/apoc.conf
    <<: *common
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  antonio3a-bridge:
    external: true

volumes:
  antonio3a-mongodb-data-vol:
    external: true
  antonio3a-mongodb-config-vol:
    external: true
  antonio3a-neo4j-data-vol:
    external: true
  antonio3a-neo4j-logs-vol:
    external: true
  antonio3a-neo4j-plugins-vol:
    external: true
