x-common : &common
  networks:
    - antonio3a-bridge
  restart: unless-stopped

networks:
  antonio3a-bridge:
    external: true

services:
  mongodb:
    <<: *common
    image: mongo:8.0.8
    container_name: mongodb
    hostname: mongodb.antonio3a.aaa
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${AAA_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${AAA_PASS}
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data-vol:/data/db
      - mongodb-config-vol:/data/configdb

  neo4j:
    image: neo4j:5.26.0-enterprise
    container_name: neo4j
    hostname: neo4j.antonio3a.aaa
    environment:
      - apoc.export.file.enabled=true
      - apoc.import.file.enabled=true
      - apoc.import.file.use_neo4j_config=true
      - NEO4J_PLUGINS=["apoc", "graph-data-science"]
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_AUTH=neo4j/${AAA_PASS}
    ports:
      - "7473:7473"
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j-data-vol:/data
      - neo4j-logs-vol:/logs
      - neo4j-plugins-vol:/plugins
      - $AAA_HOME/neo4j/conf/apoc.conf:/var/lib/neo4j/conf/apoc.conf
    <<: *common
    deploy:
      resources:
        limits:
          memory: 1G

volumes:
  mongodb-data-vol:
    external: true
  mongodb-config-vol:
    external: true
  neo4j-data-vol:
    external: true
  neo4j-logs-vol:
    external: true
  neo4j-plugins-vol:
    external: true
