x-common : &common
  networks:
    - antonio3a-bridge
  restart: unless-stopped

networks:
  antonio3a-bridge:
    external: true

services:
  mysql:
    <<: *common
    image: mysql:9.3.0
    container_name: mysql
    hostname: mysql.antonio3a.aaa
    environment:
      - MYSQL_ROOT_PASSWORD=${AAA_PASS}
      - MYSQL_DATABASE=${AAA_USER}
    ports:
      - "3306:3306"
    volumes:
      - mysql-vol:/var/lib/mysql

  postgresql:
    <<: *common
    image: postgres:17.4
    container_name: postgresql
    hostname: postgresql.antonio3a.aaa
    environment:
      - POSTGRES_USER=${AAA_USER}
      - POSTGRES_PASSWORD=${AAA_PASS}
      - POSTGRES_DB=${AAA_USER}
    ports:
      - "5432:5432"
    volumes:
      - postgresql-vol:/var/lib/postgresql/data

  sqlserver:
    <<: *common
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    hostname: sqlserver.antonio3a.aaa
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${AAA_PASS}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-vol:/var/opt/mssql

volumes:
  mysql-vol:
    external: true
  postgresql-vol:
    external: true
  sqlserver-vol:
    external: true
