x-common: &common
  image: antonio3a/aaa-eureka-server
  networks:
    - aaa-bridge
  restart: unless-stopped

x-common-env: &common-env
  EUREKA_ENVIRONMENT: development
  EUREKA_CLIENT_FETCH-REGISTRY: true
  EUREKA_CLIENT_REGISTER-WITH-EUREKA: true

services:
  eureka-1:
    <<: *common
    container_name: eureka-1
    hostname: eureka1.antonio3a.aaa
    environment:
      <<: *common-env
      SERVER_PORT: 8761
      SPRING_PROFILES_ACTIVE: peer1
      eureka.client.service-url.defaultZone: http://eureka2.antonio3a.aaa:8762/eureka/, http://eureka3.antonio3a.aaa:8763/eureka/
    ports:
      - "8761:8761"

  eureka-2:
    <<: *common
    container_name: eureka-2
    hostname: eureka2.antonio3a.aaa
    environment:
      <<: *common-env
      SERVER_PORT: 8762
      SPRING_PROFILES_ACTIVE: peer2
      eureka.client.service-url.defaultZone: http://eureka1.antonio3a.aaa:8761/eureka/, http://eureka3.antonio3a.aaa:8763/eureka/
    ports:
      - "8762:8762"

  eureka-3:
    <<: *common
    container_name: eureka-3
    hostname: eureka3.antonio3a.aaa
    environment:
      <<: *common-env
      SERVER_PORT: 8763
      SPRING_PROFILES_ACTIVE: peer3
      eureka.client.service-url.defaultZone: http://eureka1.antonio3a.aaa:8761/eureka/, http://eureka2.antonio3a.aaa:8762/eureka/
    ports:
      - "8763:8763"

networks:
  aaa-bridge:
    external: true
