x-common: &common
  networks:
    - antonio3a-bridge
  restart: always

networks:
  antonio3a-bridge:
    external: true

services:
  gitlab:
    <<: *common
    image: gitlab/gitlab-ee:17.5.0-ee.0
    container_name: antonio3a-gitlab
    hostname: gitlab.antonio3a.aaa
    ports:
      - "22:22"
      - "80:80"
      - "443:443"
    volumes:
      - antonio3a-gitlab-data-vol:/var/opt/gitlab
      - antonio3a-gitlab-config-vol:/etc/gitlab
      - antonio3a-gitlab-logs-vol:/var/log/gitlab
      - ${AAA_HOME}/ssl:/etc/gitlab/ssl
    #gitlab-rake "gitlab:password:reset[root]"

  gitlab-runner:
    <<: *common
    image: gitlab/gitlab-runner:alpine-v17.11.0
    container_name: antonio3a-gitlab-runner
    hostname: gitlab-runner.antonio3a.aaa
    privileged: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - antonio3a-gitlab-runner-home-vol:/home/gitlab-runner
      - antonio3a-gitlab-runner-config-vol:/etc/gitlab-runner

volumes:
  antonio3a-gitlab-data-vol:
    external: true
  antonio3a-gitlab-config-vol:
    external: true
  antonio3a-gitlab-logs-vol:
    external: true
  antonio3a-gitlab-runner-config-vol:
    external: true
  antonio3a-gitlab-runner-home-vol:
    external: true
