x-common : &common
  networks:
    - antonio3a-bridge
  restart: unless-stopped

services:
  grafana:
    <<: *common
    image: grafana/grafana:12.0.1
    container_name: 3A-grafana
    hostname: grafana.antonio3a.aaa
    ports:
      - "3000:3000"
    volumes:
      - grafana-vol:/var/lib/grafana

  loki:
    <<: *common
    image: grafana/loki:3.5.1
    container_name: 3A-loki
    hostname: loki.antonio3a.aaa
    ports:
      - "3100:3100"
    volumes:
      - grafana-loki-vol:/loki

  tempo:
    <<: *common
    user: root
    image: grafana/tempo:2.7.2
    container_name: 3A-tempo
    hostname: tempo.antonio3a.aaa
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "9095:9095" # tempo grpc
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
    volumes:
      - ${AAA_HOME}/tempo/tempo.yaml:/etc/tempo.yaml
      - tempo-vol:/var/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]

networks:
  antonio3a-bridge:
    external: true

volumes:
  grafana-vol:
    external: true
  loki-vol:
    external: true
  tempo-vol:
    external: true