x-common : &common
  networks:
    - antonio3a-bridge
  restart: unless-stopped

services:
  grafana:
    <<: *common
    image: grafana/grafana:11.4.0
    container_name: grafana
    hostname: grafana.antonio3a.aaa
    ports:
      - "3000:3000"
    volumes:
      - grafana-vol:/var/lib/grafana

  loki:
    <<: *common
    image: grafana/loki:3.3.2
    container_name: loki
    hostname: loki.antonio3a.aaa
    ports:
      - "3100:3100"
    volumes:
      - grafana-loki-vol:/loki

  tempo:
    <<: *common
    image: grafana/tempo:2.6.1
    container_name: tempo
    hostname: tempo.antonio3a.aaa
    ports:
      - "3200:3200"
      - "9411:9411"
    volumes:
      - ${AAA_HOME}/tempo/tempo.yaml:/etc/tempo.yaml
    command: [ "-config.file=/etc/tempo.yaml" ]

networks:
  antonio3a-bridge:
    external: true

volumes:
  grafana-vol:
    external: true
  grafana-loki-vol:
    external: true