services:
  keycloak:
    image: keycloak/keycloak:26.1.4-0
    container_name: keycloak
    hostname: keycloak.antonio3a.aaa
    environment:
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgresql.antonio3a.aaa:5432/antonio3a_keycloak
      - KC_DB_USERNAME=${AAA_USER}
      - KC_DB_PASSWORD=${AAA_PASS}
      - KC_BOOTSTRAP_ADMIN_USERNAME=${AAA_USER}
      - KC_BOOTSTRAP_ADMIN_PASSWORD=${AAA_PASS}
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - antonio3a-bridge
    restart: always
    command: [
      "start-dev",
      "--features=token-exchange",
    ]
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  antonio3a-bridge:
    external: true
