services:
  minio:
    image: minio/minio:RELEASE.2024-12-18T13-15-44Z
    container_name: antonio3a-minio
    hostname: minio.antonio3a.aaa
    environment:
      - MINIO_ROOT_USER=${AAA_USER}
      - MINIO_ROOT_PASSWORD=${AAA_PASS}
    ports:
      - "9100:9000"
      - "9001:9001"
    volumes:
      - antonio3a-minio-vol:/data
    networks:
      - antonio3a-bridge
    restart: always
    command: server /data --console-address ":9001"

networks:
  antonio3a-bridge:
    external: true

volumes:
  antonio3a-minio-vol:
    external: true
