x-common : &common
  networks:
    - antonio3a-bridge
  restart: always

services:
  prometheus:
    <<: *common
    image: prom/prometheus:v2.54.1
    container_name: antonio3a-prometheus
    hostname: prometheus.antonio3a.aaa
    ports:
      - "9090:9090"
    volumes:
      - ${AAA_HOME}/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - antonio3a-prometheus-vol:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-remote-write-receiver

  opentelemetry-collector:
    <<: *common
    image: otel/opentelemetry-collector-contrib:0.111.0
    container_name: antonio3a-opentelemetry-collector
    hostname: opentelemetry-collector.antonio3a.aaa
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus' metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "55679:55679" # zpages extension
    volumes:
      - ${AAA_HOME}/opentelemetry-collector/otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml

  jaeger-all-in-one:
    <<: *common
    image: jaegertracing/all-in-one:1.62.0
    container_name: antonio3a-jaeger
    hostname: jaeger.antonio3a.aaa
    environment:
      #- COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "16686:16686"

networks:
  antonio3a-bridge:
    external: true

volumes:
  antonio3a-prometheus-vol:
    external: true