services:
  openproject:
    image: openproject/openproject:14.6.1
    container_name: antonio3a-openproject
    hostname: openproject.antonio3a.aaa
    restart: always
    environment:
      - OPENPROJECT_HTTPS=false
      - OPENPROJECT_SECRET_KEY_BASE=1234secret5678
      - OPENPROJECT_HOST__NAME=openproject.antonio3a.aaa
      - OPENPROJECT_DEFAULT__LANGUAGE=en
      - DATABASE_URL=postgres://antonio3a:${AAA_PASS}@antonio3a-postgresql/antonio3a_openproject_db
    ports:
      - "8080:80"
    volumes:
      - antonio3a-openproject-data-vol:/var/openproject/assets
    networks:
      - antonio3a-bridge

networks:
  antonio3a-bridge:
    external: true

volumes:
  antonio3a-openproject-data-vol:
    external: true