services:
  openproject:
    image: openproject/openproject:14.6.1
    container_name: openproject
    hostname: openproject.antonio3a.aaa
    restart: unless-stopped
    environment:
      - OPENPROJECT_HTTPS=false
      - OPENPROJECT_SECRET_KEY_BASE=1234secret5678
      - OPENPROJECT_HOST__NAME=openproject.antonio3a.aaa
      - OPENPROJECT_DEFAULT__LANGUAGE=en
      - DATABASE_URL=postgres://antonio3a:${AAA_PASS}@postgresql/antonio3a_openproject_db
    ports:
      - "8080:80"
    volumes:
      - openproject-data-vol:/var/openproject/assets
    networks:
      - aaa-bridge

networks:
  aaa-bridge:
    external: true

volumes:
  openproject-data-vol:
    external: true