x-common : &common
  networks:
    - aaa-bridge
  restart: always

networks:
  3A-bridge:
    external: true

services:
  portainer:
    <<: *common
    image: portainer/portainer-ce:${PORTAINER_VERSION}
    container_name: aaa-portainer
    hostname: portainer.antonio3a.aaa
    ports:
#      - "8000:8000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - aaa-portainer-data-vol:/data

  portainer-agent:
    <<: *common
    image: portainer/agent:${PORTAINER_VERSION}
    container_name: aaa-portainer-agent
    hostname: portainer-agent.antonio3a.aaa
    ports:
      - "9001:9001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

volumes:
  aaa-portainer-data-vol:
    external: true
