x-common: &common
  networks:
    - antonio3a-bridge
  restart: unless-stopped

networks:
  antonio3a-bridge:
    external: true

services:
  sonarqube:
    <<: *common
    image: sonarqube:25.4.0.105899-community
    container_name: sonarqube
    hostname: sonarqube.antonio3a.aaa
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://postgresql/sonarqube_db
      - SONAR_JDBC_USERNAME=${AAA_USER}
      - SONAR_JDBC_PASSWORD=${AAA_PASS}
    ports:
      - "0:9000"
    volumes:
      - sonarqube-data-vol:/opt/sonarqube/data
      - sonarqube-logs-vol:/opt/sonarqube/logs
      - sonarqube-extensions-vol:/opt/sonarqube/extensions

volumes:
  sonarqube-data-vol:
    external: true
  sonarqube-logs-vol:
    external: true
  sonarqube-extensions-vol:
    external: true
