node.name: antonio3a-logstash
xpack:
  monitoring:
    enabled: true
    allow_legacy_collection: true
    elasticsearch:
      username: ${AAA_USER}
      password: ${AAA_PASS}
      hosts:
        - "https://elasticsearch01.antonio3a.aaa:9200"
        - "https://elasticsearch02.antonio3a.aaa:9200"
        - "https://elasticsearch03.antonio3a.aaa:9200"
