name: nginx-proxy-manager

x-common: &common
  networks:
    - aaa-bridge
  restart: always

services:
  nginx-proxy-manager:
    <<: *common
    image: jc21/nginx-proxy-manager:2.14.0
    hostname: nginx-proxy-manager.antonio3a.aaa
    container_name: aaa-nginx-proxy-manager
    ports:
      - "80:80"
      - "443:443"
      - "127.0.0.1:81:81"
    environment:
      INITIAL_ADMIN_EMAIL: ${AAA_EMAIL}
      INITIAL_ADMIN_PASSWORD: ${AAA_PASS}
      DB_POSTGRES_HOST: aaa-postgresql
      DB_POSTGRES_PORT: 5432
      DB_POSTGRES_USER: ${AAA_USER}
      DB_POSTGRES_PASSWORD: ${AAA_PASS}
      DB_POSTGRES_NAME: nginx_proxy_manager
    volumes:
      - aaa-nginx-proxy-manager-data-vol:/data
      - aaa-nginx-proxy-manager-letsencrypt-vol:/etc/letsencrypt

networks:
  aaa-bridge:
    external: true

volumes:
  aaa-nginx-proxy-manager-data-vol:
  aaa-nginx-proxy-manager-letsencrypt-vol:
