x-common : &common
  networks:
    - aaa-bridge
  restart: always

networks:
  aaa-bridge:
    external: true

services:
  mysql:
    <<: *common
    image: mysql:9.6.0
    container_name: aaa-mysql
    hostname: mysql.antonio3a.aaa
    environment:
      - MYSQL_ROOT_PASSWORD=${AAA_PASS}
      - MYSQL_DATABASE=${AAA_USER}
    ports:
      - "3306:3306"
    volumes:
      - aaa-mysql-vol:/var/lib/mysql

  postgresql:
    <<: *common
    image: postgres:18.3
    container_name: aaa-postgresql
    hostname: postgresql.antonio3a.aaa
    environment:
      - POSTGRES_USER=${AAA_USER}
      - POSTGRES_PASSWORD=${AAA_PASS}
      - POSTGRES_DB=${AAA_USER}
    ports:
      - "5432:5432"
    volumes:
      - ${AAA_HOME}/ssl:/var/lib/postgresql/data/certs:ro
      - aaa-postgresql-vol:/var/lib/postgresql/data

  sqlserver:
    <<: *common
    image: mcr.microsoft.com/mssql/server:2025-latest
    container_name: aaa-sqlserver
    hostname: sqlserver.antonio3a.aaa
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${AAA_PASS}
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - aaa-sqlserver-vol:/var/opt/mssql

volumes:
  aaa-mysql-vol:
  aaa-postgresql-vol:
  aaa-sqlserver-vol:
